name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  install:
    if: contains(github.server_url, 'git.atlastechsolutions.co.uk')
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}
      - name: Install Node
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -y -qq nodejs npm
      - run: npm install
